import { PlusOutlined } from '@ant-design/icons';
import { App, Button, Empty, Input, Spin, Typography } from 'antd';
import { useEffect, useState } from 'react';

import { gitRepositoriesApi } from '../../api';
import type { GitRepositoryDto, RepoIndexDto } from '../../autogenerated';
import { extractApiErrorMessage } from '../../utils/errors';
import { CreateRepositoryModal } from './components/CreateRepositoryModal';
import { RepositoryCard } from './components/RepositoryCard';

const { Title, Text, Paragraph } = Typography;
const { Search } = Input;

interface RepoWithIndex extends GitRepositoryDto {
  index?: RepoIndexDto;
}

export const RepositoriesListPage = () => {
  const { message } = App.useApp();
  const [loading, setLoading] = useState(true);
  const [deleting, setDeleting] = useState<string | null>(null);
  const [reindexing, setReindexing] = useState<string | null>(null);
  const [repositories, setRepositories] = useState<RepoWithIndex[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);

  const fetchRepositories = async () => {
    try {
      const [reposRes, indexesRes] = await Promise.all([
        gitRepositoriesApi.getRepositories(),
        gitRepositoriesApi.getRepoIndexes(),
      ]);

      const repos = reposRes.data || [];
      const indexes = indexesRes.data || [];

      const reposWithIndexes: RepoWithIndex[] = repos.map((repo) => ({
        ...repo,
        index: indexes.find(
          (idx) =>
            idx.repositoryId === repo.id && idx.branch === repo.defaultBranch,
        ),
      }));

      setRepositories(reposWithIndexes);
    } catch (e) {
      console.error('Error fetching repositories:', e);
      const errorMessage = extractApiErrorMessage(
        e,
        'Failed to load repositories',
      );
      setError(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const fetchSingleRepository = async (repositoryId: string) => {
    try {
      const [repoRes, indexRes] = await Promise.all([
        gitRepositoriesApi.getRepositoryById(repositoryId),
        gitRepositoriesApi.getRepoIndexByRepositoryId(repositoryId),
      ]);

      const repo = repoRes.data;
      const index = indexRes.data as RepoIndexDto | undefined;

      const updatedRepo: RepoWithIndex = {
        ...repo,
        index,
      };

      setRepositories((prev) =>
        prev.map((r) => (r.id === repositoryId ? updatedRepo : r)),
      );
    } catch (e) {
      console.error('Error fetching repository:', e);
      const errorMessage = extractApiErrorMessage(
        e,
        'Failed to refresh repository',
      );
      message.error(errorMessage);
    }
  };

  useEffect(() => {
    (async () => {
      await fetchRepositories();
    })();
  }, []);

  const handleDeleteRepository = async (repositoryId: string) => {
    setDeleting(repositoryId);
    try {
      await gitRepositoriesApi.deleteRepository(repositoryId);
      setRepositories((prev) =>
        prev.filter((repo) => repo.id !== repositoryId),
      );
      message.success('Repository deleted successfully');
    } catch (e: unknown) {
      console.error('Error deleting repository:', e);
      const errorMessage = extractApiErrorMessage(
        e,
        'Failed to delete repository',
      );
      message.error(errorMessage);
    } finally {
      setDeleting(null);
    }
  };

  const filteredRepositories = repositories.filter((repo) => {
    if (!searchTerm) return true;
    const lowerSearch = searchTerm.toLowerCase();
    return (
      repo.owner?.toLowerCase().includes(lowerSearch) ||
      repo.repo?.toLowerCase().includes(lowerSearch) ||
      repo.url?.toLowerCase().includes(lowerSearch)
    );
  });

  const stats = repositories.reduce(
    (acc, repo) => {
      acc.total += 1;
      const status = repo.index?.status;
      if (status === 'completed') {
        acc.indexed += 1;
      } else if (status === 'in_progress') {
        acc.indexing += 1;
      } else if (status === 'failed') {
        acc.failed += 1;
      }
      return acc;
    },
    { total: 0, indexed: 0, indexing: 0, failed: 0 },
  );

  if (loading) {
    return (
      <div
        style={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          height: '50vh',
        }}>
        <Spin size="large" />
      </div>
    );
  }

  if (error) {
    return (
      <div style={{ padding: 24, textAlign: 'center' }}>
        <Text type="danger">{error}</Text>
      </div>
    );
  }

  return (
    <div
      style={{
        minHeight: '100%',
      }}>
      <div
        style={{
          background: 'white',
          padding: 24,
        }}>
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            gap: 24,
            flexWrap: 'wrap',
          }}>
          <div>
            <Title level={2} style={{ marginBottom: 4 }}>
              Git Repositories
            </Title>
            <Paragraph type="secondary" style={{ marginBottom: 0 }}>
              Manage repositories and track indexing progress
            </Paragraph>
          </div>
          <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
            <Button
              type="primary"
              icon={<PlusOutlined />}
              size="middle"
              onClick={() => setIsCreateModalOpen(true)}>
              Add Repository
            </Button>
          </div>
        </div>

        <div
          style={{
            marginTop: 20,
            display: 'flex',
            flexWrap: 'wrap',
            gap: 32,
            alignItems: 'center',
          }}>
          <Search
            placeholder="Search repositories..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            allowClear
            size="large"
            style={{ width: 340, maxWidth: '100%' }}
          />
          <div style={{ display: 'flex', gap: 20, flexWrap: 'wrap' }}>
            {[
              { label: 'Total', value: stats.total },
              { label: 'Indexed', value: stats.indexed, color: '#16a34a' },
              { label: 'Indexing', value: stats.indexing, color: '#1d4ed8' },
              { label: 'Failed', value: stats.failed, color: '#b91c1c' },
            ].map((item) => (
              <div key={item.label}>
                <Text
                  style={{
                    fontSize: 12,
                    letterSpacing: 1,
                    color: '#94a3b8',
                  }}>
                  {item.label.toUpperCase()}{' '}
                  <span
                    style={{
                      color: item.color || '#0f172a',
                    }}>
                    {item.value}
                  </span>
                </Text>
              </div>
            ))}
          </div>
        </div>
      </div>

      {repositories.length === 0 ? (
        <Empty
          description="No repositories found"
          image={Empty.PRESENTED_IMAGE_SIMPLE}>
          <Button type="primary" onClick={() => setIsCreateModalOpen(true)}>
            Add your first repository
          </Button>
        </Empty>
      ) : filteredRepositories.length === 0 ? (
        <div style={{ marginTop: 48 }}>
          <Empty description={`No repositories match "${searchTerm}"`} />
        </div>
      ) : (
        <div
          style={{
            display: 'flex',
            flexWrap: 'wrap',
            gap: 24,
            padding: 24,
          }}>
          {filteredRepositories.map((repo) => (
            <RepositoryCard
              key={repo.id}
              repo={repo}
              deleting={deleting}
              reindexing={reindexing}
              onDelete={handleDeleteRepository}
              onReindexStart={setReindexing}
              onReindexEnd={() => setReindexing(null)}
              onRefresh={fetchSingleRepository}
            />
          ))}
        </div>
      )}

      <CreateRepositoryModal
        open={isCreateModalOpen}
        onClose={() => setIsCreateModalOpen(false)}
        onSuccess={fetchRepositories}
      />
    </div>
  );
};
