import type { JsonValue } from 'type-fest';

import type {
  ThreadMessageDto,
  ThreadMessageDtoRequestTokenUsage,
} from '../../../../autogenerated';

export interface ToolCallFunction {
  name?: string;
  arguments?: string | Record<string, unknown>;
  title?: string;
  __title?: string;
}

export interface ToolCall {
  id?: string;
  name?: string;
  function?: ToolCallFunction;
  args?: string | Record<string, unknown>;
  title?: string;
  __title?: string;
}

export interface ShellResult {
  command?: string;
  exitCode?: number;
  output?: string;
  stdout?: string;
  stderr?: string;
  [key: string]: unknown;
}

export type MessagePayload = ThreadMessageDto['message'];

export type ToolRenderStatus = 'calling' | 'executed' | 'stopped';

export type PreparedMessage =
  | {
      type: 'system';
      message: ThreadMessageDto;
      id: string;
      nodeId?: string;
      createdAt?: string;
      inCommunicationExec?: boolean;
      sourceAgentNodeId?: string;
    }
  | {
      type: 'reasoning';
      message: ThreadMessageDto;
      id: string;
      nodeId?: string;
      createdAt?: string;
      inCommunicationExec?: boolean;
      sourceAgentNodeId?: string;
    }
  | {
      type: 'chat';
      message: ThreadMessageDto;
      id: string;
      nodeId?: string;
      createdAt?: string;
      inCommunicationExec?: boolean;
      sourceAgentNodeId?: string;
    }
  | {
      type: 'tool';
      name: string;
      status: ToolRenderStatus;
      result?: unknown;
      id: string;
      toolKind?: 'generic' | 'shell';
      shellCommand?: string;
      toolOptions?: Record<string, JsonValue>;
      requestTokenUsage?: ThreadMessageDtoRequestTokenUsage | null;
      requestTokenUsageIn?: ThreadMessageDtoRequestTokenUsage | null;
      requestTokenUsageOut?: ThreadMessageDtoRequestTokenUsage | null;
      nodeId?: string;
      createdAt?: string;
      roleLabel?: string;
      title?: string;
      inCommunicationExec?: boolean;
      sourceAgentNodeId?: string;
    };
