import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router';
import {
  Button,
  Card,
  Dropdown,
  Empty,
  Input,
  Modal,
  message,
  Spin,
  Tag,
  Typography,
} from 'antd';
import { EllipsisOutlined, PlusOutlined } from '@ant-design/icons';
import { graphsApi } from '../../api';
import type { GraphDto } from '../../autogenerated';
import { formatDistanceToNow } from 'date-fns';

const { Title, Text, Paragraph } = Typography;
const { Search } = Input;

const STATUS_META: Record<
  NonNullable<GraphDto['status']> | 'draft',
  { label: string; color: string; bg: string }
> = {
  running: { label: 'Running', color: '#166534', bg: '#bbf7d0' },
  compiling: { label: 'Compiled', color: '#1d4ed8', bg: '#dbeafe' },
  created: { label: 'Created', color: '#1d4ed8', bg: '#dbeafe' },
  stopped: { label: 'Stopped', color: '#4b5563', bg: '#e5e7eb' },
  error: { label: 'Error', color: '#b91c1c', bg: '#fee2e2' },
  draft: { label: 'Draft', color: '#92400e', bg: '#fed7aa' },
};

export const GraphsListPage = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [deleting, setDeleting] = useState<string | null>(null);
  const [graphs, setGraphs] = useState<GraphDto[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [searchTerm, setSearchTerm] = useState('');

  useEffect(() => {
    let mounted = true;
    (async () => {
      try {
        const res = await graphsApi.getAllGraphs();
        if (!mounted) return;
        setGraphs(res.data || []);
      } catch (e) {
        if (!mounted) return;
        console.error('Error fetching graphs:', e);
        setError('Failed to load graphs');
      } finally {
        if (mounted) setLoading(false);
      }
    })();
    return () => {
      mounted = false;
    };
  }, []);

  const handleCreateGraph = async () => {
    try {
      const res = await graphsApi.createGraph({
        name: `New Graph ${new Date().toLocaleString()}`,
        description: 'A new graph',
        schema: {
          nodes: [],
          edges: [],
        },
      });

      const graphId = res.data.id;
      message.success('Graph created successfully');
      navigate(`/graphs/${graphId}`);
    } catch (e: unknown) {
      console.error('Error creating graph:', e);
      const errorMessage =
        e instanceof Error ? e.message : 'Failed to create graph';
      message.error(errorMessage);
    }
  };

  const handleDeleteGraph = async (graphId: string) => {
    setDeleting(graphId);
    try {
      await graphsApi.deleteGraph(graphId);
      setGraphs((prev) => prev.filter((graph) => graph.id !== graphId));
      message.success('Graph deleted successfully');
    } catch (e: unknown) {
      console.error('Error deleting graph:', e);
      const errorMessage =
        e instanceof Error ? e.message : 'Failed to delete graph';
      message.error(errorMessage);
    } finally {
      setDeleting(null);
    }
  };

  const handleEditGraph = (graphId: string) => {
    navigate(`/graphs/${graphId}`);
  };

  const confirmDeleteGraph = (graphId: string) => {
    Modal.confirm({
      title: 'Delete graph',
      content:
        'Are you sure you want to delete this graph? This action cannot be undone.',
      okText: 'Delete',
      okButtonProps: { danger: true, loading: deleting === graphId },
      cancelText: 'Cancel',
      centered: true,
      onOk: () => handleDeleteGraph(graphId),
    });
  };

  const getNodeCount = (graph: GraphDto) => {
    return graph.schema?.nodes?.length || 0;
  };

  const getStatusMeta = (graph: GraphDto) => {
    if (graph.temporary) {
      return STATUS_META.draft;
    }
    const normalizedStatus =
      graph.status?.toLowerCase() as keyof typeof STATUS_META;

    if (normalizedStatus && STATUS_META[normalizedStatus]) {
      return STATUS_META[normalizedStatus];
    }
    return { label: 'Active', color: '#0f172a', bg: '#e5e7eb' };
  };

  const filteredGraphs = graphs.filter((graph) => {
    if (!searchTerm) return true;
    return graph.name?.toLowerCase().includes(searchTerm.toLowerCase());
  });

  const stats = graphs.reduce(
    (acc, graph) => {
      acc.total += 1;
      const normalized = graph.status?.toLowerCase();
      if (normalized === 'running') {
        acc.running += 1;
      } else if (normalized === 'stopped') {
        acc.stopped += 1;
      }
      if (graph.temporary) {
        acc.drafts += 1;
      }
      return acc;
    },
    { total: 0, running: 0, stopped: 0, drafts: 0 },
  );

  if (loading) {
    return (
      <div
        style={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          height: '50vh',
        }}>
        <Spin size="large" />
      </div>
    );
  }

  if (error) {
    return (
      <div style={{ padding: 24, textAlign: 'center' }}>
        <Text type="danger">{error}</Text>
      </div>
    );
  }

  return (
    <div
      style={{
        backgroundColor: '#f5f7fb',
        minHeight: '100%',
      }}>
      <div
        style={{
          background: 'white',
          padding: 24,
        }}>
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            gap: 24,
            flexWrap: 'wrap',
          }}>
          <div>
            <Title level={2} style={{ marginBottom: 4 }}>
              Agent Graphs
            </Title>
            <Paragraph type="secondary" style={{ marginBottom: 0 }}>
              Manage and monitor your agent workflow graphs
            </Paragraph>
          </div>
          <Button
            type="primary"
            icon={<PlusOutlined />}
            size="middle"
            onClick={handleCreateGraph}>
            New Graph
          </Button>
        </div>

        <div
          style={{
            marginTop: 20,
            display: 'flex',
            flexWrap: 'wrap',
            gap: 32,
            alignItems: 'center',
          }}>
          <Search
            placeholder="Search graphs..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            allowClear
            size="large"
            style={{ width: 340, maxWidth: '100%' }}
          />
          <div style={{ display: 'flex', gap: 20, flexWrap: 'wrap' }}>
            {[
              { label: 'Total', value: stats.total },
              { label: 'Running', value: stats.running, color: '#16a34a' },
              { label: 'Stopped', value: stats.stopped, color: '#0f172a' },
              { label: 'Drafts', value: stats.drafts, color: '#ea580c' },
            ].map((item) => (
              <div key={item.label}>
                <Text
                  style={{
                    fontSize: 12,
                    letterSpacing: 1,
                    color: '#94a3b8',
                  }}>
                  {item.label.toUpperCase()}{' '}
                  <span
                    style={{
                      color: item.color || '#0f172a',
                    }}>
                    {item.value}
                  </span>
                </Text>
              </div>
            ))}
          </div>
        </div>
      </div>

      {graphs.length === 0 ? (
        <Empty
          description="No graphs found"
          image={Empty.PRESENTED_IMAGE_SIMPLE}>
          <Button type="primary" onClick={handleCreateGraph}>
            Create your first graph
          </Button>
        </Empty>
      ) : filteredGraphs.length === 0 ? (
        <div style={{ marginTop: 48 }}>
          <Empty description={`No graphs match "${searchTerm}"`} />
        </div>
      ) : (
        <div
          style={{
            display: 'flex',
            flexWrap: 'wrap',
            gap: 24,
            padding: 24,
          }}>
          {filteredGraphs.map((graph) => {
            const statusMeta = getStatusMeta(graph);
            const updatedAt = new Date(
              graph.updatedAt || graph.createdAt || new Date().toISOString(),
            );

            return (
              <Card
                key={graph.id}
                hoverable
                onClick={() => handleEditGraph(graph.id)}
                style={{
                  borderRadius: 15,
                  border: '1px solid #e5e7eb',
                  backgroundColor: '#ffffff',
                  cursor: 'pointer',
                  flex: '0 0 clamp(280px, 28vw, 360px)',
                }}
                styles={{
                  body: {
                    padding: 15,
                    display: 'flex',
                    flexDirection: 'column',
                    height: '100%',
                  },
                }}>
                <div
                  style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'flex-start',
                    marginBottom: 16,
                  }}>
                  <div>
                    <div
                      style={{
                        fontSize: 18,
                        fontWeight: 500,
                        color: '#111827',
                        marginBottom: 5,
                      }}>
                      {graph.name}
                    </div>
                    <div
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: 12,
                      }}>
                      <Tag
                        style={{
                          margin: 0,
                          border: 'none',
                          color: statusMeta.color,
                          backgroundColor: statusMeta.bg,
                        }}>
                        {statusMeta.label}
                      </Tag>
                      <span
                        style={{
                          fontSize: 12,
                          color: '#6b7280',
                        }}>
                        v{graph.version}
                      </span>
                    </div>
                  </div>
                  <Dropdown
                    trigger={['click']}
                    menu={{
                      items: [
                        {
                          key: 'delete',
                          danger: true,
                          label: 'Delete',
                          disabled: deleting === graph.id,
                        },
                      ],
                      onClick: ({ key, domEvent }) => {
                        domEvent.stopPropagation();
                        if (key === 'delete') {
                          confirmDeleteGraph(graph.id);
                        }
                      },
                    }}>
                    <Button
                      type="text"
                      icon={<EllipsisOutlined />}
                      onClick={(event) => event.stopPropagation()}
                      style={{
                        border: 'none',
                        boxShadow: 'none',
                        color: '#6b7280',
                      }}
                    />
                  </Dropdown>
                </div>

                <Paragraph
                  style={{
                    color: '#374151',
                    fontSize: 14,
                  }}>
                  {graph.description ||
                    'Automated workflow for your agent graphs.'}
                </Paragraph>

                <div
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: 5,
                    color: '#9ca3af',
                    fontSize: 13,
                  }}>
                  <span>{getNodeCount(graph)} nodes</span>
                  <span>|</span>
                  <span>
                    Modified{' '}
                    {formatDistanceToNow(updatedAt, { addSuffix: true })}
                  </span>
                </div>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
};
