import { List } from '@refinedev/antd';
import { Card, Col, Row, Spin, Statistic } from 'antd';
import { useEffect, useState } from 'react';
import { Line } from '@ant-design/plots';
import {
  StatisticsResponseDto,
  RevenueResponseDto,
  DailyRevenueDto,
} from '../../autogenerated';
import { internalApi } from '../../api';
import { AttentionItems } from './components/attention-items';

export const MainPage = () => {
  const [statistics, setStatistics] = useState<StatisticsResponseDto | null>(
    null,
  );
  const [revenue, setRevenue] = useState<RevenueResponseDto | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [statsResponse, revenueResponse] = await Promise.all([
          internalApi.getStatistics(),
          internalApi.getRevenue(),
        ]);

        setStatistics(statsResponse.data);
        setRevenue(revenueResponse.data);
      } catch (error) {
        console.error('Error fetching data:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, []);

  return (
    <List title="Dashboard">
      {loading ? (
        <div
          style={{
            display: 'flex',
            justifyContent: 'center',
            padding: '50px',
          }}>
          <Spin size="large" />
        </div>
      ) : (
        <>
          <AttentionItems />

          <h2 style={{ marginTop: '24px', marginBottom: '16px' }}>
            General statistic
          </h2>
          <Row gutter={[16, 16]} style={{ marginTop: '24px' }}>
            <Col xs={24} sm={12} md={6} lg={4}>
              <Card>
                <Statistic
                  title="Total Revenue"
                  value={revenue?.totalRevenue || '0'}
                  valueStyle={{ color: '#52c41a' }}
                  prefix="AED"
                />
              </Card>
            </Col>
            <Col xs={24} sm={12} md={6} lg={4}>
              <Card>
                <Statistic
                  title="Total Products"
                  value={statistics?.totalProducts || 0}
                  valueStyle={{ color: '#1890ff' }}
                />
              </Card>
            </Col>
            <Col xs={24} sm={12} md={6} lg={4}>
              <Card>
                <Statistic
                  title="Total Product Options"
                  value={statistics?.totalProductOptions || 0}
                  valueStyle={{ color: '#722ed1' }}
                />
              </Card>
            </Col>
          </Row>

          <h2 style={{ marginTop: '24px', marginBottom: '16px' }}>
            Codes Status
          </h2>
          <Row gutter={[16, 16]}>
            <Col xs={24} sm={12} md={6} lg={4}>
              <Card>
                <Statistic
                  title="Total Product Codes"
                  value={statistics?.totalProductCodes || 0}
                  valueStyle={{ color: '#fa8c16' }}
                />
              </Card>
            </Col>
            <Col xs={24} sm={12} md={6} lg={4}>
              <Card>
                <Statistic
                  title="Total Active Codes"
                  value={statistics?.activeCodes || 0}
                  valueStyle={{ color: '#5cb196' }}
                />
              </Card>
            </Col>
            <Col xs={24} sm={12} md={6} lg={4}>
              <Card>
                <Statistic
                  title="Reserved Codes"
                  value={statistics?.reservedCodes || 0}
                  valueStyle={{ color: '#eb2f96' }}
                />
              </Card>
            </Col>
            <Col xs={24} sm={12} md={6} lg={4}>
              <Card>
                <Statistic
                  title="Free Codes"
                  value={statistics?.freeCodes || 0}
                  valueStyle={{ color: '#13c2c2' }}
                />
              </Card>
            </Col>
            <Col xs={24} sm={12} md={6} lg={4}>
              <Card>
                <Statistic
                  title="Free Active Codes"
                  value={statistics?.activeNonReservedCodes || 0}
                  valueStyle={{ color: '#b1825c' }}
                />
              </Card>
            </Col>
          </Row>

          <h2 style={{ marginTop: '24px', marginBottom: '16px' }}>
            Orders Status
          </h2>
          <Row gutter={[16, 16]}>
            <Col xs={24} sm={12} md={6} lg={4}>
              <Card>
                <Statistic
                  title="Total Orders"
                  value={statistics?.totalOrders || 0}
                  valueStyle={{ color: '#3f8600' }}
                />
              </Card>
            </Col>
            <Col xs={24} sm={12} md={6} lg={4}>
              <Card>
                <Statistic
                  title="Pending Orders"
                  value={statistics?.pendingOrders || 0}
                  valueStyle={{ color: '#faad14' }}
                />
              </Card>
            </Col>
            <Col xs={24} sm={12} md={6} lg={4}>
              <Card>
                <Statistic
                  title="Completed Orders"
                  value={statistics?.completedOrders || 0}
                  valueStyle={{ color: '#52c41a' }}
                />
              </Card>
            </Col>
            <Col xs={24} sm={12} md={6} lg={4}>
              <Card>
                <Statistic
                  title="Expired Orders"
                  value={statistics?.expiredOrders || 0}
                  valueStyle={{ color: '#f5222d' }}
                />
              </Card>
            </Col>
          </Row>

          <h2 style={{ marginTop: '24px', marginBottom: '16px' }}>
            Payments Status
          </h2>
          <Row gutter={[16, 16]}>
            <Col xs={24} sm={12} md={6} lg={4}>
              <Card>
                <Statistic
                  title="Pending Payments"
                  value={statistics?.pendingPayments || 0}
                  valueStyle={{ color: '#faad14' }}
                />
              </Card>
            </Col>
            <Col xs={24} sm={12} md={6} lg={4}>
              <Card>
                <Statistic
                  title="Completed Payments"
                  value={statistics?.completedPayments || 0}
                  valueStyle={{ color: '#52c41a' }}
                />
              </Card>
            </Col>
            <Col xs={24} sm={12} md={6} lg={4}>
              <Card>
                <Statistic
                  title="Failed Payments"
                  value={statistics?.failedPayments || 0}
                  valueStyle={{ color: '#f5222d' }}
                />
              </Card>
            </Col>
            <Col xs={24} sm={12} md={6} lg={4}>
              <Card>
                <Statistic
                  title="Cancelled Payments"
                  value={statistics?.cancelledPayments || 0}
                  valueStyle={{ color: '#8c8c8c' }}
                />
              </Card>
            </Col>
          </Row>

          {revenue?.dailyRevenue && revenue.dailyRevenue.length > 0 && (
            <>
              <h2 style={{ marginTop: '24px', marginBottom: '16px' }}>
                Revenue Last 30 Days
              </h2>
              <Card>
                <div style={{ height: '200px' }}>
                  <Line
                    data={revenue.dailyRevenue.map((day: DailyRevenueDto) => ({
                      date: day.date,
                      revenue: parseFloat(day.revenue || '0'),
                    }))}
                    xField="date"
                    yField="revenue"
                    seriesField="revenue"
                    isStack={true}
                    animation={true}
                    color="#52c41a"
                    smooth={true}
                    legend={false}
                    tooltip={{
                      formatter: (datum) => {
                        return {
                          name: 'Revenue',
                          value: `AED${datum.revenue}`,
                        };
                      },
                    }}
                    yAxis={{
                      label: {
                        formatter: (v) => `AED${v}`,
                      },
                    }}
                  />
                </div>
              </Card>
            </>
          )}
        </>
      )}
    </List>
  );
};
