import '@uiw/react-md-editor/markdown-editor.css';

import MDEditor from '@uiw/react-md-editor';
import type { FormInstance } from 'antd';
import { Button, Form, Input, Modal, Select, Space } from 'antd';

import type { KnowledgeDocDto } from '../../../autogenerated';

export type KnowledgeFormValues = {
  title: string;
  tags?: string[];
};

type KnowledgeEditorModalProps = {
  open: boolean;
  activeDoc: KnowledgeDocDto | null;
  saving: boolean;
  form: FormInstance<KnowledgeFormValues>;
  editorValue: string;
  onEditorChange: (nextValue: string) => void;
  tagOptions: string[];
  onCancel: () => void;
  onSubmit: () => void;
  onOpenAiSuggestion: () => void;
  aiActionLabel: string;
};

export const KnowledgeEditorModal = ({
  open,
  activeDoc,
  saving,
  form,
  editorValue,
  onEditorChange,
  tagOptions,
  onCancel,
  onSubmit,
  onOpenAiSuggestion,
  aiActionLabel,
}: KnowledgeEditorModalProps) => {
  return (
    <Modal
      title={activeDoc ? 'Edit knowledge' : 'Create knowledge'}
      open={open}
      onCancel={onCancel}
      onOk={onSubmit}
      okText={activeDoc ? 'Save' : 'Create'}
      okButtonProps={{ loading: saving }}
      destroyOnClose
      width={900}>
      <Form layout="vertical" form={form}>
        <Form.Item
          name="title"
          label="Title"
          rules={[{ required: true, message: 'Title is required' }]}>
          <Input placeholder="Knowledge title" />
        </Form.Item>
        <Form.Item
          label={
            <Space align="center">
              <span>Content</span>
              <Button
                type="link"
                size="small"
                style={{ padding: 0, height: 'auto', fontSize: 12 }}
                onClick={onOpenAiSuggestion}>
                {aiActionLabel}
              </Button>
            </Space>
          }>
          <div data-color-mode="light">
            <MDEditor
              value={editorValue}
              onChange={(value) => onEditorChange(value || '')}
              height={320}
              preview="live"
            />
          </div>
        </Form.Item>
        <Form.Item name="tags" label="Tags">
          <Select
            mode="tags"
            placeholder="Add tags"
            options={tagOptions.map((tag) => ({ label: tag, value: tag }))}
            tokenSeparators={[',']}
          />
        </Form.Item>
      </Form>
    </Modal>
  );
};
