import { Button, Input, Modal, Select, Space, Typography } from 'antd';
import type { FC } from 'react';

import type { LiteLlmModelDto } from '../../../autogenerated';
import { MarkdownContent } from '../../../components/markdown/MarkdownContent';

const { Text } = Typography;

interface AnalyzeThreadModalProps {
  open: boolean;
  onCancel: () => void;
  onAnalyze: () => void;
  loading: boolean;
  disabled: boolean;
  result: string | null;
  userInput: string;
  onUserInputChange: (value: string) => void;
  model: string | undefined;
  onModelChange: (value: string | undefined) => void;
  models: LiteLlmModelDto[];
  modelsLoading: boolean;
}

export const AnalyzeThreadModal: FC<AnalyzeThreadModalProps> = ({
  open,
  onCancel,
  onAnalyze,
  loading,
  disabled,
  result,
  userInput,
  onUserInputChange,
  model,
  onModelChange,
  models,
  modelsLoading,
}) => {
  const modelOptions = models.map((m) => ({
    label: m.ownedBy ? `${m.id} (${m.ownedBy})` : m.id,
    value: m.id,
  }));

  return (
    <Modal
      title="Analyze thread"
      open={open}
      onCancel={onCancel}
      destroyOnClose
      footer={[
        <Button key="cancel" onClick={onCancel}>
          Close
        </Button>,
        <Button
          key="analyze"
          type="primary"
          onClick={onAnalyze}
          loading={loading}
          disabled={disabled}>
          Analyze
        </Button>,
      ]}>
      <Space direction="vertical" size={12} style={{ width: '100%' }}>
        <Text>
          AI will analyze this thread and share hints about improvements or
          potential problems.
        </Text>
        <div>
          <Text strong style={{ display: 'block', marginBottom: 6 }}>
            Model
          </Text>
          <Select
            value={model}
            onChange={(value) => onModelChange(value)}
            allowClear
            showSearch
            loading={modelsLoading}
            notFoundContent={
              modelsLoading ? 'Loading models...' : 'No models available'
            }
            filterOption={(input, option) =>
              (option?.label ?? '')
                .toString()
                .toLowerCase()
                .includes(input.toLowerCase())
            }
            options={modelOptions}
            disabled={disabled || loading}
            placeholder="Select model"
            style={{ width: '100%' }}
          />
        </div>
        <Input.TextArea
          rows={4}
          placeholder="Optional context or questions for the analysis"
          value={userInput}
          onChange={(e) => onUserInputChange(e.target.value)}
          disabled={disabled || loading}
        />
        {result ? (
          <div
            style={{
              maxHeight: 360,
              overflowY: 'auto',
              padding: 12,
              border: '1px solid #f0f0f0',
              borderRadius: 8,
            }}>
            <MarkdownContent content={result} />
          </div>
        ) : (
          <Text type="secondary">
            Run the analysis to see AI feedback for this thread.
          </Text>
        )}
      </Space>
    </Modal>
  );
};
