import type { ThreadMessageDto } from '../../../autogenerated';

export type MessageTokenUsage = {
  totalTokens?: number;
  totalPrice?: number;
};

export type MessageAdditionalKwargs = Record<string, unknown> & {
  __runId?: string;
  __threadId?: string;
  __createdAt?: string;
  __model?: string;
  __title?: string;

  // Used by message transformer for reasoning + LLM visibility controls
  __reasoningId?: string;
  __hideForLlm?: boolean;
  __hideForSummary?: boolean;
  __isAgentInstructionMessage?: boolean;

  __context?: unknown;

  // Per-message token usage (totalTokens + totalPrice only)
  // Full TokenUsage breakdown belongs to thread-level state, not individual messages.
  __tokenUsage?: MessageTokenUsage;
};

export interface PendingMessage {
  content: string;
  role: 'human' | 'ai';
  additionalKwargs?: MessageAdditionalKwargs;
  createdAt?: string;
}

export type MessageScopeKey = string | 'all';

export type MessagesState = Record<
  string,
  Record<MessageScopeKey, ThreadMessageDto[]>
>;

export type PendingMessagesState = Record<
  string,
  Record<MessageScopeKey, PendingMessage[]>
>;

export type MessagesUpdater = (
  threadId: string,
  updater: (prev: ThreadMessageDto[]) => ThreadMessageDto[],
  nodeId?: string,
) => void;

export type PendingMessagesUpdater = (
  threadId: string,
  updater: (prev: PendingMessage[]) => PendingMessage[],
  nodeId?: string,
) => void;
