import type { ThreadMessageDto } from '../../../autogenerated';

export interface PendingMessage {
  content: string;
  role: 'human' | 'ai';
  additionalKwargs?: {
    run_id?: string;
    created_at?: string;
    [key: string]: unknown;
  };
  createdAt?: string;
}

export type MessageScopeKey = string | 'all';

export type MessagesState = Record<
  string,
  Record<MessageScopeKey, ThreadMessageDto[]>
>;

export type PendingMessagesState = Record<
  string,
  Record<MessageScopeKey, PendingMessage[]>
>;

export type MessagesUpdater = (
  threadId: string,
  updater: (prev: ThreadMessageDto[]) => ThreadMessageDto[],
  nodeId?: string,
) => void;

export type PendingMessagesUpdater = (
  threadId: string,
  updater: (prev: PendingMessage[]) => PendingMessage[],
  nodeId?: string,
) => void;

