import {
  Alert,
  Avatar,
  Button,
  Card,
  Empty,
  Input,
  Modal,
  Space,
  Tag,
  Typography,
} from 'antd';
import { createTwoFilesPatch } from 'diff';
import { useMemo } from 'react';

import type { SuggestGraphInstructionsResponseDtoUpdatesInner } from '../../../autogenerated';
import { DiffHtmlView } from '../../../components/markdown/DiffHtmlView';
import { getAgentAvatarDataUri } from '../../../utils/agentAvatars';
import { getTemplateKindColor } from '../../../utils/templateColors';
import type { GraphNode, GraphNodeData } from '../types';

const { Text } = Typography;

type GraphAiSuggestionModalProps = {
  open: boolean;
  agentNodes: GraphNode[];
  selectedNodeId: string | null;
  updatesByNodeId: Record<
    string,
    SuggestGraphInstructionsResponseDtoUpdatesInner
  >;
  userRequest: string;
  loading: boolean;
  canSubmit: boolean;
  showRunningWarning: boolean;
  onClose: () => void;
  onSelectNode: (nodeId: string) => void;
  onUserRequestChange: (value: string) => void;
  onSubmit: () => void;
  onApply: () => void;
  getCurrentInstructions: (node: GraphNode) => string;
};

const getNodeData = (node: GraphNode): GraphNodeData =>
  node.data as GraphNodeData;

export const GraphAiSuggestionModal = ({
  open,
  agentNodes,
  selectedNodeId,
  updatesByNodeId,
  userRequest,
  loading,
  canSubmit,
  showRunningWarning,
  onClose,
  onSelectNode,
  onUserRequestChange,
  onSubmit,
  onApply,
  getCurrentInstructions,
}: GraphAiSuggestionModalProps) => {
  const selectedNode =
    agentNodes.find((node) => node.id === selectedNodeId) ?? null;
  const selectedUpdate = selectedNodeId
    ? updatesByNodeId[selectedNodeId]
    : undefined;
  const hasUpdates = Object.keys(updatesByNodeId).length > 0;

  const diffText = useMemo(() => {
    if (!selectedNode || !selectedUpdate) return '';
    const current = getCurrentInstructions(selectedNode);
    const suggested = selectedUpdate.instructions ?? '';
    const diffString = createTwoFilesPatch(
      'Current',
      'Suggested',
      current,
      suggested,
      '',
      '',
      { context: Number.MAX_SAFE_INTEGER },
    );
    return diffString.trimEnd();
  }, [getCurrentInstructions, selectedNode, selectedUpdate]);

  if (!open) {
    return null;
  }

  return (
    <Modal
      title="Improve workflow with AI"
      open={open}
      onCancel={onClose}
      footer={null}
      destroyOnClose
      width={1200}>
      <Space direction="vertical" size="large" style={{ width: '100%' }}>
        {showRunningWarning && (
          <Alert
            type="warning"
            showIcon
            message="Start the graph to use AI suggestions"
          />
        )}
        <div>
          <Text strong style={{ display: 'block', marginBottom: 8 }}>
            Agents
          </Text>
          {agentNodes.length === 0 ? (
            <Empty description="No agent nodes in this graph" />
          ) : (
            <div
              style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
                gap: 12,
              }}>
              {agentNodes.map((node) => {
                const data = getNodeData(node);
                const isSelected = node.id === selectedNodeId;
                const hasUpdate = Boolean(updatesByNodeId[node.id]);
                const kind = data.templateKind ?? 'Agent';
                return (
                  <Card
                    key={node.id}
                    size="small"
                    hoverable
                    onClick={() => onSelectNode(node.id)}
                    style={{
                      border: isSelected
                        ? '1px solid #1890ff'
                        : hasUpdate
                          ? '1px solid #52c41a'
                          : '1px solid #d9d9d9',
                      borderRadius: 8,
                      boxShadow: isSelected
                        ? '0 4px 12px rgba(24, 144, 255, 0.2)'
                        : '0 2px 8px rgba(0, 0, 0, 0.08)',
                      background: '#ffffff',
                    }}
                    styles={{
                      body: {
                        padding: 0,
                      },
                    }}>
                    <div
                      style={{
                        background: '#F3F6FF',
                        padding: 12,
                        borderBottom: '1px solid #dfdfdf',
                        borderRadius: '8px 8px 0 0',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        gap: 12,
                      }}>
                      <Space size={8} align="center">
                        <Avatar
                          size={24}
                          src={getAgentAvatarDataUri(node.id, 48)}
                        />
                        <Text
                          strong
                          style={{
                            fontSize: 14,
                            overflow: 'hidden',
                            textOverflow: 'ellipsis',
                            whiteSpace: 'nowrap',
                            maxWidth: 180,
                            display: 'block',
                          }}>
                          {data.label || `Node ${node.id.slice(-6)}`}
                        </Text>
                      </Space>
                      {hasUpdate && (
                        <Tag color="green" style={{ margin: 0, fontSize: 10 }}>
                          Updated
                        </Tag>
                      )}
                    </div>
                    <div style={{ padding: 10 }}>
                      <Space size={6} wrap>
                        <Tag
                          color={getTemplateKindColor(kind)}
                          style={{ margin: 0, fontSize: 10 }}>
                          {kind}
                        </Tag>
                        <Tag
                          color="geekblue"
                          style={{ margin: 0, fontSize: 10 }}>
                          {data.template}
                        </Tag>
                      </Space>
                    </div>
                  </Card>
                );
              })}
            </div>
          )}
        </div>

        <div>
          <Text strong style={{ display: 'block', marginBottom: 6 }}>
            What should be improved?
          </Text>
          <Input.TextArea
            value={userRequest}
            onChange={(e) => onUserRequestChange(e.target.value)}
            placeholder="Describe the workflow improvements for all agents"
            autoSize={{ minRows: 3, maxRows: 6 }}
          />
          <div
            style={{
              marginTop: 8,
              display: 'flex',
              justifyContent: 'flex-end',
            }}>
            <Button
              type="primary"
              onClick={onSubmit}
              loading={loading}
              disabled={!canSubmit || loading || !userRequest.trim()}>
              Send
            </Button>
          </div>
        </div>

        <div>
          <Text strong style={{ display: 'block', marginBottom: 6 }}>
            Suggested instructions
          </Text>
          {selectedNode && selectedUpdate ? (
            <div style={{ maxHeight: 420, overflow: 'auto' }}>
              <DiffHtmlView diff={diffText} />
            </div>
          ) : (
            <Text type="secondary">
              {selectedNode
                ? 'No updates for this agent yet.'
                : 'Select an agent to view changes.'}
            </Text>
          )}
        </div>

        <div
          style={{
            marginTop: 12,
            display: 'flex',
            justifyContent: 'flex-end',
          }}>
          <Space>
            <Button onClick={onClose}>Close</Button>
            <Button type="primary" onClick={onApply} disabled={!hasUpdates}>
              Apply updates
            </Button>
          </Space>
        </div>
      </Space>
    </Modal>
  );
};
