import { Modal, Typography } from 'antd';

import type { ThreadDto, ThreadMessageDto } from '../../../autogenerated';
import type { TriggerNodeInfo } from '../../../utils/graphThreads';
import ThreadChatPanel from '../../chats/components/ThreadChatPanel';
import type {
  MessagesUpdater,
  PendingMessage,
  PendingMessagesUpdater,
} from '../types/messages';

interface ThreadChatModalProps {
  chatThread: ThreadDto | null;
  graphId: string | undefined;
  graphLoaded: boolean;
  onClose: () => void;
  triggerNodes: TriggerNodeInfo[];
  nodeDisplayNames: Record<string, string>;
  defaultNewMessageMode: 'inject_after_tool_call' | 'wait_for_completion';
  messages: ThreadMessageDto[];
  messagesLoading: boolean;
  hasMoreMessages: boolean;
  loadingMoreMessages: boolean;
  pendingMessages: PendingMessage[];
  externalThreadId: string | undefined;
  onLoadMoreMessages: () => void;
  onUpdateSharedMessages: MessagesUpdater;
  onUpdatePendingMessages: PendingMessagesUpdater;
}

export const ThreadChatModal = ({
  chatThread,
  graphId,
  graphLoaded,
  onClose,
  triggerNodes,
  nodeDisplayNames,
  defaultNewMessageMode,
  messages,
  messagesLoading,
  hasMoreMessages,
  loadingMoreMessages,
  pendingMessages,
  externalThreadId,
  onLoadMoreMessages,
  onUpdateSharedMessages,
  onUpdatePendingMessages,
}: ThreadChatModalProps) => (
  <Modal
    open={Boolean(chatThread && graphLoaded)}
    onCancel={onClose}
    footer={null}
    width={900}
    bodyStyle={{
      height: '70vh',
      display: 'flex',
      flexDirection: 'column',
    }}
    title={
      chatThread ? (
        <Typography.Text
          ellipsis={{
            tooltip: `Thread chat — ${
              chatThread.name || chatThread.id.slice(-6)
            }`,
          }}
          style={{
            display: 'inline-block',
            maxWidth: 'calc(100% - 64px)',
          }}>
          {`Thread chat — ${chatThread.name || chatThread.id.slice(-6)}`}
        </Typography.Text>
      ) : undefined
    }
    destroyOnClose>
    {chatThread && graphId ? (
      <ThreadChatPanel
        graphId={graphId}
        thread={chatThread}
        triggerNodes={triggerNodes}
        nodeDisplayNames={nodeDisplayNames}
        graphLoaded
        newMessageMode={defaultNewMessageMode}
        messages={messages}
        messagesLoading={messagesLoading}
        hasMoreMessages={hasMoreMessages}
        loadingMoreMessages={loadingMoreMessages}
        pendingMessages={pendingMessages}
        externalThreadId={externalThreadId}
        onLoadMoreMessages={onLoadMoreMessages}
        onUpdateSharedMessages={onUpdateSharedMessages}
        onUpdatePendingMessages={onUpdatePendingMessages}
      />
    ) : null}
  </Modal>
);
