import { BarChartOutlined, LoadingOutlined } from '@ant-design/icons';
import { Card, Divider, Space, Statistic, Table, Tag, Typography } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import React from 'react';

import { ThreadUsageStatisticsDto } from '../../../autogenerated';

const { Text } = Typography;

interface ThreadUsageDisplayProps {
  usage: ThreadUsageStatisticsDto | null;
  loading: boolean;
  error: string | null;
  nodeDisplayNames?: Record<string, string>;
  nodeKinds?: Record<string, string>;
}

const formatNumber = (num?: number | null): string => {
  if (typeof num !== 'number' || !Number.isFinite(num)) return '—';
  return new Intl.NumberFormat('en-US').format(num);
};

const formatUsd = (amount?: number | null): string => {
  if (typeof amount !== 'number' || !Number.isFinite(amount)) return '$—';
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 4,
    maximumFractionDigits: 4,
  }).format(amount);
};

export const ThreadUsageDisplay: React.FC<ThreadUsageDisplayProps> = ({
  usage,
  loading,
  error,
  nodeDisplayNames = {},
  nodeKinds = {},
}) => {
  if (loading) {
    return (
      <Card size="small" style={{ marginTop: 8 }}>
        <Space>
          <LoadingOutlined spin />
          <Text type="secondary">Loading usage statistics...</Text>
        </Space>
      </Card>
    );
  }

  if (error) {
    return (
      <Card size="small" style={{ marginTop: 8 }}>
        <Text type="danger">{error}</Text>
      </Card>
    );
  }

  if (!usage) {
    return null;
  }

  const { total, requests, byNode, byTool, toolsAggregate, messagesAggregate } =
    usage;

  // Prepare byNode data
  const byNodeData = byNode
    ? Object.entries(byNode).map(([nodeId, stats]) => ({
        nodeId,
        nodeName: nodeDisplayNames[nodeId] || nodeId,
        nodeKind: nodeKinds[nodeId] || 'Node',
        ...stats,
      }))
    : [];

  const toolColumns: ColumnsType<(typeof byTool)[0]> = [
    {
      title: 'Tool Name',
      dataIndex: 'toolName',
      key: 'toolName',
      ellipsis: true,
    },
    {
      title: 'Call Count',
      dataIndex: 'callCount',
      key: 'callCount',
      render: formatNumber,
      align: 'right',
    },
    {
      title: 'Total Tokens',
      dataIndex: 'totalTokens',
      key: 'totalTokens',
      render: formatNumber,
      align: 'right',
    },
    {
      title: 'Total Price',
      dataIndex: 'totalPrice',
      key: 'totalPrice',
      render: formatUsd,
      align: 'right',
    },
  ];

  return (
    <Card
      size="small"
      title={
        <Space>
          <BarChartOutlined />
          <Text strong>Thread Usage Statistics</Text>
        </Space>
      }
      style={{ marginTop: 8 }}>
      {/* Total Statistics */}
      <div style={{ marginBottom: 16 }}>
        <Text
          strong
          style={{ fontSize: 13, display: 'block', marginBottom: 8 }}>
          Total Usage
        </Text>
        <Space size="large" wrap>
          {typeof requests === 'number' && (
            <Statistic
              title="Requests"
              value={formatNumber(requests)}
              valueStyle={{ fontSize: 16 }}
            />
          )}
          <Statistic
            title="Total Tokens"
            value={formatNumber(total.totalTokens)}
            valueStyle={{ fontSize: 16 }}
          />
          <Statistic
            title="Input Tokens"
            value={formatNumber(total.inputTokens)}
            valueStyle={{ fontSize: 16 }}
          />
          {typeof total.cachedInputTokens === 'number' && (
            <Statistic
              title="Cached Input"
              value={formatNumber(total.cachedInputTokens)}
              valueStyle={{ fontSize: 16 }}
            />
          )}
          <Statistic
            title="Output Tokens"
            value={formatNumber(total.outputTokens)}
            valueStyle={{ fontSize: 16 }}
          />
          {typeof total.reasoningTokens === 'number' && (
            <Statistic
              title="Reasoning"
              value={formatNumber(total.reasoningTokens)}
              valueStyle={{ fontSize: 16 }}
            />
          )}
          {typeof total.totalPrice === 'number' && (
            <Statistic
              title="Total Cost"
              value={formatUsd(total.totalPrice)}
              valueStyle={{ fontSize: 16 }}
            />
          )}
          {typeof total.currentContext === 'number' && (
            <Statistic
              title="Current Context"
              value={formatNumber(total.currentContext)}
              valueStyle={{ fontSize: 16 }}
            />
          )}
        </Space>
      </div>

      <Divider style={{ margin: '12px 0' }} />

      {/* Messages and Tools Aggregates - in one line */}
      {(messagesAggregate || toolsAggregate) && (
        <>
          <div style={{ marginBottom: 16 }}>
            <div
              style={{
                display: 'flex',
                gap: 32,
                flexWrap: 'wrap',
              }}>
              {messagesAggregate && (
                <div style={{ flex: '1 1 300px' }}>
                  <Text
                    strong
                    style={{ fontSize: 13, display: 'block', marginBottom: 8 }}>
                    Messages Aggregate
                  </Text>
                  <Space size="middle" wrap>
                    <Statistic
                      title="Requests"
                      value={formatNumber(messagesAggregate.requestCount)}
                      valueStyle={{ fontSize: 14 }}
                    />
                    <Statistic
                      title="Tokens"
                      value={formatNumber(messagesAggregate.totalTokens)}
                      valueStyle={{ fontSize: 14 }}
                    />
                    {typeof messagesAggregate.totalPrice === 'number' && (
                      <Statistic
                        title="Cost"
                        value={formatUsd(messagesAggregate.totalPrice)}
                        valueStyle={{ fontSize: 14 }}
                      />
                    )}
                  </Space>
                </div>
              )}
              {toolsAggregate && (
                <div style={{ flex: '1 1 300px' }}>
                  <Text
                    strong
                    style={{ fontSize: 13, display: 'block', marginBottom: 8 }}>
                    Tools Aggregate
                  </Text>
                  <Space size="middle" wrap>
                    <Statistic
                      title="Requests"
                      value={formatNumber(toolsAggregate.requestCount)}
                      valueStyle={{ fontSize: 14 }}
                    />
                    <Statistic
                      title="Tokens"
                      value={formatNumber(toolsAggregate.totalTokens)}
                      valueStyle={{ fontSize: 14 }}
                    />
                    {typeof toolsAggregate.totalPrice === 'number' && (
                      <Statistic
                        title="Cost"
                        value={formatUsd(toolsAggregate.totalPrice)}
                        valueStyle={{ fontSize: 14 }}
                      />
                    )}
                  </Space>
                </div>
              )}
            </div>
          </div>
          <Divider style={{ margin: '12px 0' }} />
        </>
      )}

      {/* Usage by Agent - Always expanded, as table */}
      {byNodeData.length > 0 && (
        <div style={{ marginBottom: 16 }}>
          <Text
            strong
            style={{ fontSize: 13, display: 'block', marginBottom: 12 }}>
            Usage by Agent ({byNodeData.length})
          </Text>
          <Table
            dataSource={byNodeData}
            columns={[
              {
                title: 'Agent',
                dataIndex: 'nodeName',
                key: 'nodeName',
                render: (name: string, record: (typeof byNodeData)[0]) => (
                  <div>
                    <div
                      style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                      <Text strong>{name}</Text>
                      <Tag
                        style={{
                          fontSize: 10,
                          lineHeight: '16px',
                          padding: '0 6px',
                          margin: 0,
                        }}>
                        {record.nodeKind}
                      </Tag>
                    </div>
                    {record.nodeName !== record.nodeId && (
                      <Text type="secondary" style={{ fontSize: 11 }}>
                        {record.nodeId}
                      </Text>
                    )}
                  </div>
                ),
              },
              {
                title: 'Total Tokens',
                dataIndex: 'totalTokens',
                key: 'totalTokens',
                render: formatNumber,
                align: 'right' as const,
              },
              {
                title: 'Input',
                dataIndex: 'inputTokens',
                key: 'inputTokens',
                render: formatNumber,
                align: 'right' as const,
              },
              {
                title: 'Output',
                dataIndex: 'outputTokens',
                key: 'outputTokens',
                render: formatNumber,
                align: 'right' as const,
              },
              {
                title: 'Cached',
                dataIndex: 'cachedInputTokens',
                key: 'cachedInputTokens',
                render: (value: number | undefined) =>
                  typeof value === 'number' && value > 0
                    ? formatNumber(value)
                    : '-',
                align: 'right' as const,
              },
              {
                title: 'Reasoning',
                dataIndex: 'reasoningTokens',
                key: 'reasoningTokens',
                render: (value: number | undefined) =>
                  typeof value === 'number' && value > 0
                    ? formatNumber(value)
                    : '-',
                align: 'right' as const,
              },
              {
                title: 'Total Price',
                dataIndex: 'totalPrice',
                key: 'totalPrice',
                render: formatUsd,
                align: 'right' as const,
              },
            ]}
            pagination={false}
            size="small"
            scroll={{ x: 'max-content' }}
            rowKey="nodeId"
          />
        </div>
      )}

      {/* Usage by Tool - Always expanded */}
      {byTool && byTool.length > 0 && (
        <>
          <Divider style={{ margin: '12px 0' }} />
          <div style={{ marginBottom: 16 }}>
            <Text
              strong
              style={{ fontSize: 13, display: 'block', marginBottom: 12 }}>
              Usage by Tool ({byTool.length})
            </Text>
            <Table
              dataSource={byTool}
              columns={toolColumns}
              pagination={false}
              size="small"
              scroll={{ x: 'max-content' }}
              rowKey="toolName"
            />
          </div>
        </>
      )}
    </Card>
  );
};
