import {
  BranchesOutlined,
  DeleteOutlined,
  GithubOutlined,
  ReloadOutlined,
} from '@ant-design/icons';
import { Button, Card, message, Modal, Progress, Tag, Typography } from 'antd';
import { formatDistanceToNow } from 'date-fns';

import { gitRepositoriesApi } from '../../../api';
import type { GitRepositoryDto, RepoIndexDto } from '../../../autogenerated';
import { extractApiErrorMessage } from '../../../utils/errors';

const { Text, Paragraph } = Typography;

interface RepoWithIndex extends GitRepositoryDto {
  index?: RepoIndexDto;
}

interface RepositoryCardProps {
  repo: RepoWithIndex;
  deleting: string | null;
  reindexing: string | null;
  onDelete: (id: string) => void;
  onReindexStart: (id: string) => void;
  onReindexEnd: () => void;
  onRefresh: (repositoryId: string) => void;
}

export const RepositoryCard = ({
  repo,
  deleting,
  reindexing,
  onDelete,
  onReindexStart,
  onReindexEnd,
  onRefresh,
}: RepositoryCardProps) => {
  const handleTriggerReindex = async (repositoryId: string) => {
    onReindexStart(repositoryId);
    try {
      await gitRepositoriesApi.triggerReindex({ repositoryId });
      message.success('Reindex triggered successfully');
      onRefresh(repositoryId);
    } catch (e: unknown) {
      console.error('Error triggering reindex:', e);
      const errorMessage = extractApiErrorMessage(
        e,
        'Failed to trigger reindex',
      );
      message.error(errorMessage);
    } finally {
      onReindexEnd();
    }
  };

  const confirmDeleteRepository = (repositoryId: string) => {
    Modal.confirm({
      title: 'Delete repository',
      content:
        'Are you sure you want to delete this repository? This action cannot be undone.',
      okText: 'Delete',
      okButtonProps: { danger: true, loading: deleting === repositoryId },
      cancelText: 'Cancel',
      centered: true,
      onOk: () => onDelete(repositoryId),
    });
  };

  const getIndexProgress = () => {
    if (!repo.index) return 0;

    const { status, indexedTokens, estimatedTokens } = repo.index;

    if (status === 'completed') return 100;
    if (status === 'pending') return 0;
    if (status === 'failed') return 0;

    if (
      status === 'in_progress' &&
      indexedTokens !== null &&
      indexedTokens !== undefined &&
      estimatedTokens !== null &&
      estimatedTokens !== undefined &&
      estimatedTokens > 0
    ) {
      return Math.round((indexedTokens / estimatedTokens) * 100);
    }

    return 0;
  };

  const getProgressColor = () => {
    if (!repo.index) return '#d1d5db';

    const { status } = repo.index;

    if (status === 'completed') return '#16a34a';
    if (status === 'in_progress') return '#1d4ed8';
    if (status === 'failed') return '#b91c1c';

    return '#d1d5db';
  };

  const getProgressLabel = () => {
    if (!repo.index) return 'Not indexed yet';

    const { status, indexedTokens, estimatedTokens } = repo.index;

    if (status === 'completed') {
      const tokens =
        indexedTokens !== null && indexedTokens !== undefined
          ? indexedTokens.toLocaleString()
          : '0';
      return `Indexed (${tokens} tokens)`;
    }
    if (status === 'in_progress') {
      const tokens =
        indexedTokens !== null &&
        indexedTokens !== undefined &&
        estimatedTokens !== null &&
        estimatedTokens !== undefined
          ? ` (${indexedTokens.toLocaleString()} / ~${estimatedTokens.toLocaleString()} tokens)`
          : '';
      return `Indexing...${tokens}`;
    }
    if (status === 'failed') return 'Indexing failed';
    if (status === 'pending') return 'Pending indexing';

    return 'Not indexed yet';
  };

  const updatedAt = new Date(
    repo.updatedAt || repo.createdAt || new Date().toISOString(),
  );
  const progress = getIndexProgress();
  const progressColor = getProgressColor();
  const progressLabel = getProgressLabel();

  return (
    <Card
      key={repo.id}
      hoverable
      style={{
        borderRadius: 15,
        border: '1px solid #e5e7eb',
        backgroundColor: '#ffffff',
        flex: '0 0 clamp(280px, 28vw, 360px)',
      }}
      styles={{
        body: {
          padding: 15,
          display: 'flex',
          flexDirection: 'column',
          height: '100%',
        },
      }}>
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'flex-start',
        }}>
        <div style={{ flex: 1 }}>
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 8,
            }}>
            <GithubOutlined style={{ fontSize: 16 }} />
            <div
              style={{
                fontSize: 18,
                fontWeight: 500,
                color: '#111827',
              }}>
              {repo.owner}/{repo.repo}
            </div>
          </div>
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 8,
              flexWrap: 'wrap',
            }}>
            <span
              style={{
                fontSize: 12,
                color: '#6b7280',
              }}>
              {repo.provider}
            </span>
            {repo.defaultBranch && (
              <Tag
                icon={<BranchesOutlined />}
                style={{
                  fontSize: 11,
                  margin: 0,
                }}>
                {repo.defaultBranch}
              </Tag>
            )}
          </div>
        </div>
        <Button
          type="text"
          icon={<DeleteOutlined />}
          danger
          onClick={(event) => {
            event.stopPropagation();
            confirmDeleteRepository(repo.id);
          }}
          loading={deleting === repo.id}
          style={{
            border: 'none',
            boxShadow: 'none',
          }}
        />
      </div>

      <div style={{ marginBottom: 16 }}>
        <Paragraph
          style={{
            color: '#374151',
            fontSize: 14,
            marginBottom: 4,
          }}>
          <a
            href={repo.url}
            target="_blank"
            rel="noopener noreferrer"
            onClick={(e) => e.stopPropagation()}
            style={{ color: '#1d4ed8' }}>
            {repo.url}
          </a>
        </Paragraph>
        {repo.index?.lastIndexedCommit && (
          <Text
            style={{
              fontSize: 11,
              color: '#9ca3af',
              fontFamily: 'monospace',
            }}>
            sha: {repo.index.lastIndexedCommit}
          </Text>
        )}
      </div>

      <div style={{ marginBottom: 12 }}>
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
          }}>
          <Text style={{ fontSize: 12, color: '#6b7280' }}>
            {progressLabel}
          </Text>
          <Button
            type="text"
            icon={<ReloadOutlined />}
            size="small"
            onClick={(event) => {
              event.stopPropagation();
              onRefresh(repo.id);
            }}
            style={{
              border: 'none',
              boxShadow: 'none',
              color: '#6b7280',
              padding: '0 4px',
            }}
          />
        </div>
        <div style={{ position: 'relative' }}>
          <Progress
            percent={progress}
            showInfo={false}
            strokeColor={progressColor}
            trailColor="#f3f4f6"
            size={{ height: 12 }}
          />
        </div>
      </div>

      {repo.index?.errorMessage && (
        <div
          style={{
            padding: 8,
            background: '#fee2e2',
            borderRadius: 4,
            marginBottom: 12,
          }}>
          <Text style={{ fontSize: 12, color: '#b91c1c' }}>
            {repo.index.errorMessage}
          </Text>
        </div>
      )}

      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: 12,
          marginTop: 'auto',
        }}>
        <Text style={{ fontSize: 13, color: '#9ca3af' }}>
          Updated {formatDistanceToNow(updatedAt, { addSuffix: true })}
        </Text>
        <Button
          type="primary"
          size="small"
          icon={<ReloadOutlined />}
          onClick={(event) => {
            event.stopPropagation();
            handleTriggerReindex(repo.id);
          }}
          loading={reindexing === repo.id}
          disabled={
            reindexing === repo.id || repo.index?.status === 'in_progress'
          }>
          Reindex
        </Button>
      </div>
    </Card>
  );
};
