import { ThreadDto, ThreadDtoStatusEnum } from '../autogenerated';

export const THREAD_STATUS_STYLES: Record<
  ThreadDto['status'],
  { label: string; color: string }
> = {
  [ThreadDtoStatusEnum.Running]: { label: 'Running', color: '#1890ff' },
  [ThreadDtoStatusEnum.Done]: { label: 'Done', color: '#52c41a' },
  [ThreadDtoStatusEnum.NeedMoreInfo]: {
    label: 'Need More Info',
    color: '#faad14',
  },
  [ThreadDtoStatusEnum.Stopped]: { label: 'Stopped', color: '#ff4d4f' },
} as const;

export const getThreadStatusDisplay = (status?: ThreadDto['status']) => {
  if (!status) return null;
  return (
    THREAD_STATUS_STYLES[status] ?? {
      label: status.replace(/_/g, ' '),
      color: '#d9d9d9',
    }
  );
};


